### ISSUE TITLE
[REQUEST] Villagers should use doors as when they use normal doors

### ISSUE THREAD

**Issue by Jukabofy** [TheFizzWare/DramaticDoors#10]
**Is your feature request related to a problem? Please describe.**
I was seeing this mod for the first time, I'm creating a map, but I found that villagers don't use these custom doors

**Describe the solution you'd like**
It could be possible to include somehow these custom doors in the interactive system of the villagers, thats all

**Describe alternatives you've considered**
If you don't how to, not problem, I guess that's pretty complicated

Thanks for this mod

**Comment by Kitteh6660** [comment]
This is now implemented as of mod version 1.6.0 for Minecraft 1.18.2!
