### ISSUE TITLE
[REQUEST] Undergarden compat

### ISSUE THREAD

**Issue by Xaidee** [TheFizzWare/DramaticDoors#11]
It'd be awesome to see some tall undergarden doors. The doors needed would be a grongle door, smogstem door, and wigglewood door. I have made some textures for them already if you'd like to use them.

![tall_grongle_door](https://user-images.githubusercontent.com/59002946/169753919-aab22461-541c-45de-87c4-53a775980ac4.png) ![tall_smogstem_door](https://user-images.githubusercontent.com/59002946/169753926-df3ce93e-e0de-406e-90a0-1dd029852b1f.png) ![tall_wigglewood_door](https://user-images.githubusercontent.com/59002946/169753928-5a7299b2-b4d9-4a8a-affb-d9411437e3f2.png)

![tall_grongle_door_top](https://user-images.githubusercontent.com/59002946/169753410-72ee47d4-fd70-42ff-a88a-c152f09f9cd6.png) ![tall_smogstem_door_top](https://user-images.githubusercontent.com/59002946/169753449-a2d6e714-189e-403b-8b46-1bd50b4098e6.png) ![tall_wigglewood_door_top](https://user-images.githubusercontent.com/59002946/169753463-266d829c-af3c-4955-9ec7-c6d0a2b9c291.png)
![tall_grongle_door_middle](https://user-images.githubusercontent.com/59002946/169753408-f1210d91-0cb2-4e88-81b6-d3a3a5fe5db0.png) ![tall_smogstem_door_middle](https://user-images.githubusercontent.com/59002946/169753448-9332abb3-1437-4724-8e82-6c56c088aa66.png) ![tall_wigglewood_door_middle](https://user-images.githubusercontent.com/59002946/169753461-5038aec6-e433-439a-94bd-fd0fd27474a6.png)
![tall_grongle_door_bottom](https://user-images.githubusercontent.com/59002946/169753404-25418268-7393-4b04-a1d7-b9e1ed7f71e9.png) ![tall_smogstem_door_bottom](https://user-images.githubusercontent.com/59002946/169753445-ce30ea59-20d5-4b8d-8708-2703f5822059.png) ![tall_wigglewood_door_bottom](https://user-images.githubusercontent.com/59002946/169753459-dccef702-3685-4c92-9125-07942ba6f431.png)

**Comment by Kitteh6660** [comment]
Thank you! I can use the door textures and I can look to implement it in the next version of Dramatic Doors for Forge.
If possible, can you send over a ZIP file of the assets?

**Comment by Xaidee** [comment]
Love your work, and i'm looking forward to it!
Here you go:  [textures.zip](https://github.com/TheFizzWare/DramaticDoors/files/8752754/textures.zip)

**Comment by Xaidee** [comment]
wait i realised i messed up a couple pixels on one of the doors, heres the zip with fixed files

**Comment by Xaidee** [comment]
[textures.zip](https://github.com/TheFizzWare/DramaticDoors/files/8752893/textures.zip)

**Comment by Kitteh6660** [comment]
Thank you! I can get around to adding the tall doors.

**Comment by Kitteh6660** [comment]
Should be added in version 1.6.4 of Dramatic Doors Forge now.
