### ISSUE TITLE
Doors invisible! Like a glass doors![BUG]

### ISSUE THREAD

**Issue by Karpainen** [TheFizzWare/DramaticDoors#12]
Hey,
dramatic doors aint workin correctly. They looks like a glass. I have SEUS PTGI HHR Shader. Tall doors works fine when I turn off the shaders.

**Important Information**
Minecraft Version: **1.18.2**
Forge Version: **Fabric 0.14.6**
DramaticDoors Version: **Beta**

**Screenshots**
Tall doors are like a glass and it seems some water flow effect...
![2022-05-23_17 23 57](https://user-images.githubusercontent.com/106092599/169841428-9c4cad30-7bc8-4023-9d09-762b6a66ba2a.png)

**Comment by Kitteh6660** [comment]
Changed the rendering from Translucent to Cutout, this should hopefully fix the issues. Feel free to reopen if you have issues.
