### ISSUE TITLE
[BUG] Crash on joining worlds with Lithium

### ISSUE THREAD

**Issue by SplendidAlakey** [TheFizzWare/DramaticDoors#14]
**Important Information**

Minecraft Version: **1.18.2**
Fabric API Version: **0.53.4** + loader 0.14.6
DramaticDoors Version: **1.1**

**Describe the bug**

When [Lithium](https://www.curseforge.com/minecraft/mc-mods/lithium) and Dramatic Doors are installed together, the game crashes upon joining a world.

**To Reproduce**

1. Simply install both mods and try to join any world

**Expected behavior**

No crash.

**Logs**

https://gist.github.com/Footage2-Amply-Pounce/d20ac0348092ecce32131821d35be024

**Comment by Kitteh6660** [comment]
There is a workaround to this issue. Lithium doesn't seem to play well with mods that use mixins, especially LVT.

In lithium.properties file, add the following line:
 `mixin.ai.pathing=false`

**Comment by SplendidAlakey** [comment]
Can confirm the workaround works, but will leave the issue open in case there can be made a fix from your side. So far Dramatic Doors is the only one that caused this issue and ideally I'd like to keep the ai pathfinding optimization from Lithium as it's a pretty significant one.

**Comment by Kitteh6660** [comment]
Should be fixed with version 1.1.1 of Dramatic Doors Fabric.
