### ISSUE TITLE
[BUG] Crash : (Unsupported mob type for DoorInteractGoal)

### ISSUE THREAD

**Issue by Gbergz** [TheFizzWare/DramaticDoors#15]
Thank you for reporting!

 * Crash: [crash](https://gist.github.com/Gbergz/14b27662fc1c4c69b89adbfd23c961e0)

**Important Information**
Minecraft Version: 1.18.2
Forge Version: 40.1.30
DramaticDoors Version: 1.6.4

**Describe the bug**
Unsupported mob type for DoorInteractGoal (AI)

**To Reproduce**
Not entirely sure since this is on a public server with quite a few people.

**Expected behavior**
Not for it to crash.

**Comment by Kitteh6660** [comment]
Try the new version 1.6.4_1, this should hopefully fix the crashes.
