### ISSUE TITLE
[REQUEST] Double Doors works with Mods

### ISSUE THREAD

**Issue by ScorchedPork** [TheFizzWare/DramaticDoors#18]
## **Information**
Add functionality of working with Couplings mod by HeckinChloe and / or Double Doors mod by Serilum.

## **Feature description**
When building a grand entrance with two doors, it would be great to have the ability to have both open at once.

**Comment by Kitteh6660** [comment]
Double doors mod work with Dramatic Doors already. The main repository is outdated.

However, I will look into Fabric version of the functionality.

**Comment by ScorchedPork** [comment]
Yes please! I should have mentioned that I am using Fabric 1.19, and is where I am running into the issue.

**Comment by Kitteh6660** [comment]
Version 1.3.0 of Fabric version of Dramatic Doors should have the functionality if you have Fabric version of Double Doors installed.
