### ISSUE TITLE
[REQUEST] Compatibility with upcoming Chipped update

### ISSUE THREAD

**Issue by Illios42** [TheFizzWare/DramaticDoors#19]
**Is your feature request related to a problem? Please describe.**
It is not a problem per se but it'd would be a great enhancement to your mod. The Chipped team, basically a mod like Chisel but maintained, a much nicer style and using ingame workbenches to convert the textures of a block, is currently overhauling their alternative block textures and adding some for doors too. Seeing as your mod is so great on compat (seriously, much respect, I love it) with other popular mods this might be a really good one to add to the collection.

**Describe the solution you'd like**
Obviously there is the option of replicating the mod's style and adding them yourself.

**Describe alternatives you've considered**
The Chipped devs also talked about making the next update, after the texture overhaul, about mod compatibility. Perhaps getting in contact with them about it could be useful, especially if you want to implement the doors via the workbench system of the main mod.

**Additional context**
Here is an image of W.I.P door textures the Chipped devs released a while back:

![image](https://user-images.githubusercontent.com/101580687/180798449-4bcac835-054a-41f0-bd66-c81ad5d59563.png)

**Comment by Kitteh6660** [comment]
Here we go again and I did Macaw's Doors support recently. It's going to take a long time but it's a possibility.

The textures are amazing. But now that's 168 whole new doors!

It would help greatly if there are efforts into making tall door texture files! <3

**Comment by Illios42** [comment]
It's definitively a big project, I will ngl lmao. I asked about it on their discord as they were taking suggestions as well on what compat they should add, perhaps something will come of that in the future. If not, I will be trying my hand at making some of the textures myself once their update comes out to ease the load but I am kind of new-ish with pixel art so that could get interesting lol

It's also not tragic if it doesn't happen but something about mods working seamlessly together with compat like this just makes me really happy and probably a lot of mod-pack makers as well.

Update: I got a reponse from a Chipped dev! It's looking really good :D

<img width="610" alt="Screenshot 2022-07-27 at 13 11 46" src="https://user-images.githubusercontent.com/101580687/181233545-2532739b-c2ce-48b7-b421-be2716cfd6ac.png">

Perhaps a collab for the update after the texture rework is due xD

**Comment by Kitteh6660** [comment]
That sounds good! Once the textures are settled, work can start. I've even got the data-gen for producing model JSON files.

**Comment by Kitteh6660** [comment]
Update: Work has started. I've coded in the functionality alongside data JSON files. Now only textures remain, they're currently placeholder.

**Comment by Kitteh6660** [comment]
Another update: Chipped support has been added to both Forge and Fabric version of Dramatic Doors! Starting in Forge mod version 2.1.4 and Fabric mod version 1.3.4.
