### ISSUE TITLE
[BUG] Doors dosn't open (outdated master branch?)

### ISSUE THREAD

**Issue by puggan** [TheFizzWare/DramaticDoors#2]
Is this git-repo outdated?
According to the git repo it is version 1.0.1
https://github.com/TheFizzWare/DramaticDoors/blob/eb351f2299ea7858ccb80ca75fa5589c4e0d01fc/src/main/resources/META-INF/mods.toml#L6
But on [curse](https://www.curseforge.com/minecraft/mc-mods/dramatic-doors/files/2996644) there is an 1.1.0 version that do works.

**Important Information**
Minecraft Version: 1.16.1
Forge Version: 32.0.108
DramaticDoors Version: master (1.0.1?) eb351f2

**Describe the bug**
When clicking a door, it stay closed.

**To Reproduce**
1. place a door
2. open it

**Expected behavior**
The door should open, just as it do with the 1.1.0 release.

**Screenshots**
Master eb351f2:
![2020-09-29_12 22 58](https://user-images.githubusercontent.com/866668/94546751-9e365e80-024e-11eb-9cc1-22b82aeb1e14.png)

Curse 1.1.0:
![2020-09-29_12 18 37](https://user-images.githubusercontent.com/866668/94546779-a7bfc680-024e-11eb-8a1b-f75c6c1b7f21.png)

**Comment by TheFizzWare** [comment]
Good catch. Should be resolved now!

I did, in fact, neglect to push my local master branch to the git-repo.
