### ISSUE TITLE
[BUG] Fabric server Lagging

### ISSUE THREAD

**Issue by soldeeex** [TheFizzWare/DramaticDoors#20]
**Important Information**
Minecraft Version: **1.18.2**
Fabric Version: **0.14.8**
DramaticDoors Version: **Fabric-1.18.2-1.3.0**

**Describe the bug**
For some reason the mod causes my server to have random lag spikes. Also there is no door of the mod placed.

Spark profile: https://spark.lucko.me/ImORy0BpdX

**Screenshot**
![Screenshot 2022-08-07 at 01-36-18 spark](https://user-images.githubusercontent.com/22576855/183269103-045125dc-1da1-4c40-900d-db8f67e1076a.png)

**Mod List**
https://gist.github.com/soldeeex/973428fbc442af40b812a97af5e7ce66

**Comment by Kitteh6660** [comment]
I made some adjustments to the Mixin in version 1.3.1 of Dramatic Doors Fabric, does it help with the issues?

**Comment by soldeeex** [comment]
Yes! Now on the server there doesn't seem to be any lag spikes.
Thank you!
