### ISSUE TITLE
[BUG] Supplementaries Tall Netherite Door is missing sounds

### ISSUE THREAD

**Issue by Illios42** [TheFizzWare/DramaticDoors#21]
**Important Information**
Minecraft Version: 1.19
Forge Version: 41.1.0
DramaticDoors Version: 2.1.1.
Supplementaries: 2.0.9

**Describe the bug**
The tall netherite door from Supplementaries is missing opening sounds (normal sized netherite door has them!).

**To Reproduce**
- Install both Dramatic Doors & Supplementaries
- Place down a tall netherite door and open it

**Expected behavior**
The door should have sound effects.

**Comment by Kitteh6660** [comment]
Thanks, I was able to find out that it doesn't call for playing sounds. Will be fixed in version 2.1.2.

**Comment by Kitteh6660** [comment]
Fixed in version 2.1.2 of Dramatic Doors.
