### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by closeshot** [TheFizzWare/DramaticDoors#22]
Add additional doors

If possible add a 3x3 door that can fit in a 3x3 door way 

Would be neat if a door can fit in a 3x3 so that when making a 3 block wide  path it looks nice instead of having the 2x2 door making the path look not symmetric.

**Comment by Kitteh6660** [comment]
Unfortunately, it's a very difficult thing to implement, as the doors do not fit with standard voxel grid. Doors that are 2 blocks wide could be possible however.

**Comment by Redd56** [comment]
ooo 2 block wide doors would be very neat
