### ISSUE TITLE
[REQUEST] Tags for each mod's tall doors

### ISSUE THREAD

**Issue by saltyseadoggo** [TheFizzWare/DramaticDoors#23]
**Is your feature request related to a problem? Please describe.**
Roughly Enough Items shows all of Dramatic Doors' doors, regardless of whether or not their required mods are loaded. I am trying to hide the unobtainable doors from REI in my modpack using KubeJS, which, at the moment, means I have to list out all of the unobtainable doors by hand.

**Describe the solution you'd like**
If Dramatic Doors included item tags for each mod's tall doors, I could list out those tags instead of needing to list every single door. For example, a `#dramaticdoors:tall_bop_doors` item tag could contain all Biomes o' Plenty tall doors, and, if a modpack maker doesn't have BoP in their pack, they can use KubeJS to hide every item in the tag.~

**Describe alternatives you've considered**
There could also be a config option to hide a given mod's doors from REI. That would be even easier to use.

**Comment by Kitteh6660** [comment]
I can look into adding tags that will reside within blocks and items, under categories subfolder.

**Comment by Kitteh6660** [comment]
Version 2.1.4 will add item category tags for Forge version of Dramatic Doors.

Example tag: `dramaticdoors:categories/tall_vanilla_doors` for vanilla, `dramaticdoors:categories/tall_byg_doors` for BYG.
