### ISSUE TITLE
[REQUEST] Forbidden & Arcanus support

### ISSUE THREAD

**Issue by saltyseadoggo** [TheFizzWare/DramaticDoors#24]
**Is your feature request related to a problem? Please describe.**
This mod does not add tall versions of [Forbidden & Arcanus](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)' doors. This means that players do not have the option of building with them, and that the F&A wood sets don't have consistent offerings with other wood types when Dramatic Doors is loaded, for us consistency appreciators.

**Describe the solution you'd like**
I would like to see tall variants of F&A's Edelwood, Arcane Edelwood, Fungyss, Aurum and Cherry doors.~

**Comment by Kitteh6660** [comment]
That can easily be done! I will look to add it in next version of Dramatic Doors Forge for 1.18.2 & 1.19.2.

**Comment by Kitteh6660** [comment]
This will be added in version 2.1.4 of Dramatic Doors for Forge.
