### ISSUE TITLE
[BUG] byg dramatic doors can not be broken

### ISSUE THREAD

**Issue by Redd56** [TheFizzWare/DramaticDoors#25]
Minecraft Version: **1.19.2**
Fabric Version: **0.14.10**
DramaticDoors Version: **1.3.2**

**Describe the bug**
ebony doors act as bedrock and can not be broken

**To Reproduce**
place down an ebony door in survival
try to break it to no avail

**Expected behavior**
ebony doors to be breakable

**Comment by Kitteh6660** [comment]
I will have to look into it. Thanks for reporting!

Have you also tried breaking the block below? Does it pop off?

**Comment by Redd56** [comment]
yes they do pop off, im gonna try without any of my other mods and see if it does this in base game

**Comment by Redd56** [comment]
did some testing and it seems to only be byg ones

**Comment by Kitteh6660** [comment]
I've released version 1.3.3 of the mod that should hopefully fix the issue. The BYG doors initially used translucent rendering. I've switched most of them over to cutout but translucent remains for tall doors with semi-transparent windows.

**Comment by Redd56** [comment]
forgor to say it works
