### ISSUE TITLE
[BUG] modded doors only give 1 door

### ISSUE THREAD

**Issue by Redd56** [TheFizzWare/DramaticDoors#26]
**Important Information**
Minecraft Version: **1.19.2**
Fabric Version: **0.14.10**
DramaticDoors Version: **1.3.2**

**Description**
any door that isnt a vanilla varient gives only one door

**Expected**
to get 2 doors

**Screenshots**
![image](https://user-images.githubusercontent.com/12189828/197276394-bf7855bf-b87e-4be7-9012-810881a058d8.png)

**Comment by Kitteh6660** [comment]
I will look into it, thanks for reporting!

**Comment by Kitteh6660** [comment]
The fix has been applied to 1.18.2 and will eventually be brought to 1.19.2. Version 1.3.4 will contain the fix.

**Comment by Kitteh6660** [comment]
The fix is now live in version 1.3.5 of Dramatic Doors for 1.19.2 too. (I've skipped 1.3.4 to ensure code and compat parity)
