### ISSUE TITLE
[BUG] Incorrect Name Display for White Mangrove Door from BYG

### ISSUE THREAD

**Issue by LolJohn11** [TheFizzWare/DramaticDoors#27]
**Important Information**
Minecraft Version: **1.19.2**
Forge Version: **43.1.43**
DramaticDoors Version: **2.1.3**

**Describe the bug**
The block name for the Tall White Mangrove Door from [BYG](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go) is not displayed correctly in the tooltips, it shows the block ID instead,

**To Reproduce**
1. Have BYG and Dramatic Doors installed
2. Check the block name for the tall white mangrove door through JEI or WALIA/WTHIT
3. See the bug

**Expected behavior**
The door name should be displayed correctly ("Tall White Mangrove Door")

**Screenshots**
![dramatic doors bug1](https://user-images.githubusercontent.com/49366383/201667567-53b690f0-f8a4-4aea-9968-c032bc51cde8.png)
![dramatic doors bug2](https://user-images.githubusercontent.com/49366383/201670170-e00c2024-350d-42ff-b370-dc8fe1c2f0b1.png)

**Comment by Kitteh6660** [comment]
Thank you for reporting, I will look into fixing it!

**Comment by LolJohn11** [comment]
Seems to be fixed in the new mod release (version 2.1.5). Thanks for the fix!

**Comment by Kitteh6660** [comment]
It was no problem! I made sure the fix is applied and here we go! <3
