### ISSUE TITLE
[BUG] Tall Walnut Door Texture Error from Ecologics Mod

### ISSUE THREAD

**Issue by Bluyidark** [TheFizzWare/DramaticDoors#29]
Minecraft Version: 1.19.2
Fabric Version: 0.14.10
DramaticDoors Version: 1.3.3

Hi, I downloaded dramatic doors mod as well as other mods, and amongst all the doors, only the tall walnut door from Ecologics mod has this texture error. Hope it can be fixed! 

![2022-12-04_03 22 23](https://user-images.githubusercontent.com/112769984/205606264-29dad9e1-f898-4e44-b798-e75097f163c3.png)

**Comment by Kitteh6660** [comment]
Thank you, I am looking into it! I'm working on a sizable update to Fabric version of Dramatic Doors and I will ensure it gets fixed in later version.

**Comment by Kitteh6660** [comment]
I tried placing the tall walnut door, and I couldn't find the issue. Maybe it was some lighting error, try placing a block and breaking it then place down tall walnut door?

I checked the texture file, it looks correct. Maybe wrong lighting was applied? Try putting some light source blocks next to the door, this could possibly force update lighting.

**Comment by Bluyidark** [comment]
Oh thanks, it's fixed! I replaced the door with a grass block and then replaced it back with the door, the texture works fine now! Seems like it's really the issue with the lighting. Thanks a lot!

**Comment by Kitteh6660** [comment]
You're welcome! It was definitely not the texture but the lighting. I shall close this issue.
