### ISSUE TITLE
[REQUEST] Add 1.12.2

### ISSUE THREAD

**Issue by Betelgeusesupergiant** [TheFizzWare/DramaticDoors#3]
Dude. I don't like piston doors at all. I just want a 3 block tall iron door. All for my fnaf map. And the animatronics are 3 blocks tall dude. And it's only 1.12.2

**Comment by Kitteh6660** [comment]
The mod won't be backported to 1.12.2 at all. Sorry.

Part of the process of helping to phase out 1.12.2 and avoiding perpetuating the version.
