### ISSUE TITLE
[BUG] Recipes throw error messages in logs despite mod not present.

### ISSUE THREAD

**Issue by nanonestor** [TheFizzWare/DramaticDoors#6]
**Important Information**
Minecraft Version:  1.18.1
Forge Version: 39.0.44
DramaticDoors Version: DramaticDoors-1.18.1-1.4.2.jar

**Describe the bug**
[20:30:49] [Render thread/ERROR]: Parsing error loading recipe dramaticdoors:tall_azalea_door

In logs despite mod cavens_and_chasms not being installed.

**To Reproduce**

**Expected behavior**
Not to see error messages in logs about not-present mods, mod not present should disable.  I believe the following code can also be used to prevent recipes from load attempt based on mod presence.

```
    "conditions": [
        {
            "type": "forge:mod_loaded",
            "modid": "evilcraft"
        }
```

**Screenshots**
logs
[Log snip](https://paste.gg/p/anonymous/8f20d9385894486190d4a800f2264603)

**Comment by Kitteh6660** [comment]
Thanks. It should now be resolved with mod version 1.5.0. Closed now.
