### ISSUE TITLE
[REQUEST] Quark Double Door Compat

### ISSUE THREAD

**Issue by WenXin20** [TheFizzWare/DramaticDoors#8]
**Is your feature request related to a problem? Please describe.**
- Double doors don't open at the same time like normal doors do with Quark installed

**Describe the solution you'd like**
- Double tall doors should open at the same time when Quark's double doors are enabled in the config.

**Describe alternatives you've considered**
- None that I could think of.

**Comment by Kitteh6660** [comment]
Now in version 2.1.2 of Dramatic Doors.
