### ISSUE TITLE
[REQUEST] Pokecube Compat

### ISSUE THREAD

**Issue by WenXin20** [TheFizzWare/DramaticDoors#9]
**Describe the solution you'd like**
Hi, have you considered adding tall doors for [Pokecube AIO](https://www.curseforge.com/minecraft/mc-mods/pokecube-aoi)? If you'd prefer, I could see about providing the textures since I am the one who made the textures for the doors (and most items & blocks) in Pokecube.

**Comment by Kitteh6660** [comment]
Hello! Thank you for reaching out to me. I'm willing to add the tall version of the doors and I wouldn't mind being sent the textures too! The more mods supported, the better! :D

**Comment by WenXin20** [comment]
Awesome! I'll see if I have any time next week to make some textures during my spring break

**Comment by WenXin20** [comment]
Hi! I finally finished up the textures today. :)
Only thing to note is that I plan to eventually retexture the corrupted door, since it wasn't made by me and is currently just a recolor of the warped door.

[dramatic_doors_pokecube_compat.zip](https://github.com/TheFizzWare/DramaticDoors/files/8313108/dramatic_doors_pokecube_compat.zip)

I also should mention that Pokecube hasn't yet been updated to 1.18.2, since the main dev is too busy atm.

**Comment by Kitteh6660** [comment]
Thank you! I will still look to futureproof the mod and possibly add in the next release.

**Comment by WenXin20** [comment]
Sounds good!

**Comment by Kitteh6660** [comment]
The compat is now implemented! Now if only Pokecube could be updated for 1.18.2.

**Comment by WenXin20** [comment]
Awesome! Hopefully soon :D
